/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiskupijeRouteImport } from './routes/biskupije'
import { Route as BrojkeRouteImport } from './routes/brojke'
import { Route as CrkveRouteImport } from './routes/crkve'
import { Route as KartaRouteImport } from './routes/karta'
import { Route as OProjektuRouteImport } from './routes/o-projektu'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ZupeRouteImport } from './routes/zupe'
import { Route as BiskupijaSlugRouteImport } from './routes/biskupija.$slug'
import { Route as CrkvaSlugRouteImport } from './routes/crkva.$slug'
import { Route as UstanovaSlugRouteImport } from './routes/ustanova.$slug'
import { Route as ZupaSlugRouteImport } from './routes/zupa.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiskupijeRoute = BiskupijeRouteImport.update({
  id: '/biskupije',
  path: '/biskupije',
  getParentRoute: () => rootRouteImport,
} as any)
const BrojkeRoute = BrojkeRouteImport.update({
  id: '/brojke',
  path: '/brojke',
  getParentRoute: () => rootRouteImport,
} as any)
const CrkveRoute = CrkveRouteImport.update({
  id: '/crkve',
  path: '/crkve',
  getParentRoute: () => rootRouteImport,
} as any)
const KartaRoute = KartaRouteImport.update({
  id: '/karta',
  path: '/karta',
  getParentRoute: () => rootRouteImport,
} as any)
const OProjektuRoute = OProjektuRouteImport.update({
  id: '/o-projektu',
  path: '/o-projektu',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ZupeRoute = ZupeRouteImport.update({
  id: '/zupe',
  path: '/zupe',
  getParentRoute: () => rootRouteImport,
} as any)
const BiskupijaSlugRoute = BiskupijaSlugRouteImport.update({
  id: '/biskupija/$slug',
  path: '/biskupija/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrkvaSlugRoute = CrkvaSlugRouteImport.update({
  id: '/crkva/$slug',
  path: '/crkva/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UstanovaSlugRoute = UstanovaSlugRouteImport.update({
  id: '/ustanova/$slug',
  path: '/ustanova/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ZupaSlugRoute = ZupaSlugRouteImport.update({
  id: '/zupa/$slug',
  path: '/zupa/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biskupije': typeof BiskupijeRoute
  '/brojke': typeof BrojkeRoute
  '/crkve': typeof CrkveRoute
  '/karta': typeof KartaRoute
  '/o-projektu': typeof OProjektuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zupe': typeof ZupeRoute
  '/biskupija/$slug': typeof BiskupijaSlugRoute
  '/crkva/$slug': typeof CrkvaSlugRoute
  '/ustanova/$slug': typeof UstanovaSlugRoute
  '/zupa/$slug': typeof ZupaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biskupije': typeof BiskupijeRoute
  '/brojke': typeof BrojkeRoute
  '/crkve': typeof CrkveRoute
  '/karta': typeof KartaRoute
  '/o-projektu': typeof OProjektuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zupe': typeof ZupeRoute
  '/biskupija/$slug': typeof BiskupijaSlugRoute
  '/crkva/$slug': typeof CrkvaSlugRoute
  '/ustanova/$slug': typeof UstanovaSlugRoute
  '/zupa/$slug': typeof ZupaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biskupije': typeof BiskupijeRoute
  '/brojke': typeof BrojkeRoute
  '/crkve': typeof CrkveRoute
  '/karta': typeof KartaRoute
  '/o-projektu': typeof OProjektuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/zupe': typeof ZupeRoute
  '/biskupija/$slug': typeof BiskupijaSlugRoute
  '/crkva/$slug': typeof CrkvaSlugRoute
  '/ustanova/$slug': typeof UstanovaSlugRoute
  '/zupa/$slug': typeof ZupaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biskupije'
    | '/brojke'
    | '/crkve'
    | '/karta'
    | '/o-projektu'
    | '/sitemap.xml'
    | '/zupe'
    | '/biskupija/$slug'
    | '/crkva/$slug'
    | '/ustanova/$slug'
    | '/zupa/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biskupije'
    | '/brojke'
    | '/crkve'
    | '/karta'
    | '/o-projektu'
    | '/sitemap.xml'
    | '/zupe'
    | '/biskupija/$slug'
    | '/crkva/$slug'
    | '/ustanova/$slug'
    | '/zupa/$slug'
  id:
    | '__root__'
    | '/'
    | '/biskupije'
    | '/brojke'
    | '/crkve'
    | '/karta'
    | '/o-projektu'
    | '/sitemap.xml'
    | '/zupe'
    | '/biskupija/$slug'
    | '/crkva/$slug'
    | '/ustanova/$slug'
    | '/zupa/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiskupijeRoute: typeof BiskupijeRoute
  BrojkeRoute: typeof BrojkeRoute
  CrkveRoute: typeof CrkveRoute
  KartaRoute: typeof KartaRoute
  OProjektuRoute: typeof OProjektuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ZupeRoute: typeof ZupeRoute
  BiskupijaSlugRoute: typeof BiskupijaSlugRoute
  CrkvaSlugRoute: typeof CrkvaSlugRoute
  UstanovaSlugRoute: typeof UstanovaSlugRoute
  ZupaSlugRoute: typeof ZupaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biskupije': {
      id: '/biskupije'
      path: '/biskupije'
      fullPath: '/biskupije'
      preLoaderRoute: typeof BiskupijeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brojke': {
      id: '/brojke'
      path: '/brojke'
      fullPath: '/brojke'
      preLoaderRoute: typeof BrojkeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crkve': {
      id: '/crkve'
      path: '/crkve'
      fullPath: '/crkve'
      preLoaderRoute: typeof CrkveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karta': {
      id: '/karta'
      path: '/karta'
      fullPath: '/karta'
      preLoaderRoute: typeof KartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-projektu': {
      id: '/o-projektu'
      path: '/o-projektu'
      fullPath: '/o-projektu'
      preLoaderRoute: typeof OProjektuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zupe': {
      id: '/zupe'
      path: '/zupe'
      fullPath: '/zupe'
      preLoaderRoute: typeof ZupeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biskupija/$slug': {
      id: '/biskupija/$slug'
      path: '/biskupija/$slug'
      fullPath: '/biskupija/$slug'
      preLoaderRoute: typeof BiskupijaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crkva/$slug': {
      id: '/crkva/$slug'
      path: '/crkva/$slug'
      fullPath: '/crkva/$slug'
      preLoaderRoute: typeof CrkvaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustanova/$slug': {
      id: '/ustanova/$slug'
      path: '/ustanova/$slug'
      fullPath: '/ustanova/$slug'
      preLoaderRoute: typeof UstanovaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zupa/$slug': {
      id: '/zupa/$slug'
      path: '/zupa/$slug'
      fullPath: '/zupa/$slug'
      preLoaderRoute: typeof ZupaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiskupijeRoute: BiskupijeRoute,
  BrojkeRoute: BrojkeRoute,
  CrkveRoute: CrkveRoute,
  KartaRoute: KartaRoute,
  OProjektuRoute: OProjektuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ZupeRoute: ZupeRoute,
  BiskupijaSlugRoute: BiskupijaSlugRoute,
  CrkvaSlugRoute: CrkvaSlugRoute,
  UstanovaSlugRoute: UstanovaSlugRoute,
  ZupaSlugRoute: ZupaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
